In [125]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [126]:
data = pd.read_csv("hour.csv")

In [127]:
data.head()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1

In [128]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     17379 non-null  int64
 1   dteday      17379 non-null  str
 2   season      17379 non-null  int64
 3   yr          17379 non-null  int64
 4   mnth        17379 non-null  int64
 5   hr          17379 non-null  int64
 6   holiday     17379 non-null  int64
 7   weekday     17379 non-null  int64
 8   workingday  17379 non-null  int64
 9   weathersit  17379 non-null  int64
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  casual      17379 non-null  int64
 15  registered  17379 non-null  int64
 16  cnt         17379 non-null  int64
dtypes: float64(4), int64(12), str(1)
memory usage: 2.3 MB

In [129]:
data.describe()

,instant,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,17379.0000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000
mean,8690.0000,2.501640,0.502561,6.537775,11.546752,0.028770,3.003683,0.682721,1.425283,0.496987,0.475775,0.627229,0.190098,35.676218,153.786869,189.463088
std,5017.0295,1.106918,0.500008,3.438776,6.914405,0.167165,2.005771,0.465431,0.639357,0.192556,0.171850,0.192930,0.122340,49.305030,151.357286,181.387599
min,1.0000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,4345.5000,2.000000,0.000000,4.000000,6.000000,0.000000,1.000000,0.000000,1.000000,0.340000,0.333300,0.480000,0.104500,4.000000,34.000000,40.000000
50%,8690.0000,3.000000,1.000000,7.000000,12.000000,0.000000,3.000000,1.000000,1.000000,0.500000,0.484800,0.630000,0.194000,17.000000,115.000000,142.000000
75%,13034.5000,3.000000,1.000000,10.000000,18.000000,0.000000,5.000000,1.000000,2.000000,0.660000,0.621200,0.780000,0.253700,48.000000,220.000000,281.000000
max,17379.0000,4.000000,1.000000,12.000000,23.000000,1.000000,6.000000,1.000000,4.000000,1.000000,1.000000,1.000000,0.850700,367.000000,886.000000,977.000000

In [130]:
X = data.drop(["cnt", "casual", "registered", "instant", "dteday"], axis = 1)
y = data["cnt"]

In [131]:
from sklearn.model_selection import train_test_split

In [132]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [133]:
print(X_train.shape)

(13903, 12)

In [134]:
print(X_test.shape)

(3476, 12)

In [135]:
print(y_train.shape)

(13903,)

In [136]:
print(y_test.shape)

(3476,)

In [137]:
from sklearn.preprocessing import StandardScaler

In [138]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [139]:
X_test_scaled.shape

(3476, 12)

In [140]:
from sklearn.linear_model import LinearRegression

In [141]:
lr = LinearRegression()

In [142]:
lr.fit(X_train_scaled, y_train)

LinearRegression()

In [143]:
y_pred = lr.predict(X_test_scaled)

In [144]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [145]:
print("R²:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", mean_squared_error(y_test, y_pred) ** 0.5)

R²: 0.3879811583139132
MAE: 104.80335089554427
RMSE: 139.2114519989348

In [146]:
lr.coef_

array([ 22.70884768,  41.42208942,   0.40963385,  52.96072612,
        -4.02674857,   3.57532773,   1.8218643 ,  -2.19318563,
        19.11729518,  35.32069014, -38.45628117,   4.21779835])

In [147]:
from sklearn.linear_model import Ridge

ridge = Ridge(alpha=1.0)

ridge.fit(X_train_scaled, y_train)

y_pred_ridge = ridge.predict(X_test_scaled)

In [148]:
print("R²:", r2_score(y_test, y_pred_ridge))
print("MAE:", mean_absolute_error(y_test, y_pred_ridge))
print("RMSE:", mean_squared_error(y_test, y_pred_ridge) ** 0.5)

R²: 0.3879803481501569
MAE: 104.80310773108502
RMSE: 139.21154413991795

In [149]:
from sklearn.linear_model import Lasso

lasso = Lasso(alpha=1.0)

lasso.fit(X_train_scaled, y_train)

y_pred_lasso = lasso.predict(X_test_scaled)

In [150]:
print("R²:", r2_score(y_test, y_pred_lasso))
print("MAE:", mean_absolute_error(y_test, y_pred_lasso))
print("RMSE:", mean_squared_error(y_test, y_pred_lasso) ** 0.5)

R²: 0.38792487323845004
MAE: 104.55075892814213
RMSE: 139.2178532290969

In [151]:
pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": lasso.coef_
})

       Feature  Coefficient
0       season    22.040639
1           yr    40.443814
2         mnth     0.000000
3           hr    52.226695
4      holiday    -3.312309
5      weekday     2.682154
6   workingday     0.992634
7   weathersit    -1.289584
8         temp    20.959631
9        atemp    33.025716
10         hum   -38.300366
11   windspeed     3.079393

In [152]:
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor(n_neighbors=3)

knn.fit(X_train_scaled, y_train)

y_pred_knn = knn.predict(X_test_scaled)

In [153]:
print("R²:", r2_score(y_test, y_pred_knn))
print("MAE:", mean_absolute_error(y_test, y_pred_knn))
print("RMSE:", mean_squared_error(y_test, y_pred_knn) ** 0.5)

R²: 0.6448703918990479
MAE: 68.82038741848868
RMSE: 106.04397728429144

In [154]:
from sklearn.svm import SVR

svr = SVR(kernel="rbf", C=1.0, epsilon=0.1)

svr.fit(X_train_scaled, y_train)

y_pred_svr = svr.predict(X_test_scaled)

In [155]:
print("R²:", r2_score(y_test, y_pred_svr))
print("MAE:", mean_absolute_error(y_test, y_pred_svr))
print("RMSE:", mean_squared_error(y_test, y_pred_svr) ** 0.5)

R²: 0.4031686588828547
MAE: 89.19936027122863
RMSE: 137.4733061905602

In [156]:
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(
    random_state=42
)

dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

In [157]:
print("R²:", r2_score(y_test, y_pred_dt))
print("MAE:", mean_absolute_error(y_test, y_pred_dt))
print("RMSE:", mean_squared_error(y_test, y_pred_dt) ** 0.5)

R²: 0.8928514365053305
MAE: 34.1800920598389
RMSE: 58.24863377942147

In [158]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1,
    max_depth=18,
    min_samples_split=6,
    min_samples_leaf=1
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

In [159]:
print("R²:", r2_score(y_test, y_pred_rf))
print("MAE:", mean_absolute_error(y_test, y_pred_rf))
print("RMSE:", mean_squared_error(y_test, y_pred_rf) ** 0.5)

R²: 0.9439500061250312
MAE: 25.063703238331115
RMSE: 42.128922505290426

In [160]:
results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Ridge",
        "Lasso",
        "KNN",
        "SVR",
        "Decision Tree",
        "Random Forest"
    ],
    "R2": [
        r2_score(y_test, y_pred),
        r2_score(y_test, y_pred_ridge),
        r2_score(y_test, y_pred_lasso),
        r2_score(y_test, y_pred_knn),
        r2_score(y_test, y_pred_svr),
        r2_score(y_test, y_pred_dt),
        r2_score(y_test, y_pred_rf)
    ],
    "MAE": [
        mean_absolute_error(y_test, y_pred),
        mean_absolute_error(y_test, y_pred_ridge),
        mean_absolute_error(y_test, y_pred_lasso),
        mean_absolute_error(y_test, y_pred_knn),
        mean_absolute_error(y_test, y_pred_svr),
        mean_absolute_error(y_test, y_pred_dt),
        mean_absolute_error(y_test, y_pred_rf)
    ],
    "RMSE": [
        mean_squared_error(y_test, y_pred) ** 0.5,
        mean_squared_error(y_test, y_pred_ridge) ** 0.5,
        mean_squared_error(y_test, y_pred_lasso) ** 0.5,
        mean_squared_error(y_test, y_pred_knn) ** 0.5,
        mean_squared_error(y_test, y_pred_svr) ** 0.5,
        mean_squared_error(y_test, y_pred_dt) ** 0.5,
        mean_squared_error(y_test, y_pred_rf) ** 0.5
    ]
})

results.sort_values("R2", ascending=False)

               Model        R2         MAE        RMSE
6      Random Forest  0.943950   25.063703   42.128923
5      Decision Tree  0.892851   34.180092   58.248634
3                KNN  0.644870   68.820387  106.043977
4                SVR  0.403169   89.199360  137.473306
0  Linear Regression  0.387981  104.803351  139.211452
1              Ridge  0.387980  104.803108  139.211544
2              Lasso  0.387925  104.550759  139.217853

In [161]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid = {
    "n_estimators": [100, 200, 300],
    "max_depth": [10, 15, 20, 25, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": ["sqrt", "log2", 1.0]
}

rf = RandomForestRegressor(
    random_state=42,
    n_jobs=-1
)

random_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_grid,
    n_iter=20,
    cv=5,
    scoring="r2",
    n_jobs=-1,
    random_state=42
)

random_search.fit(X_train, y_train)

print("Best parameters:")
print(random_search.best_params_)

best_rf = random_search.best_estimator_

y_pred_best_rf = best_rf.predict(X_test)

print("R²:", r2_score(y_test, y_pred_best_rf))
print("MAE:", mean_absolute_error(y_test, y_pred_best_rf))
print("RMSE:", mean_squared_error(y_test, y_pred_best_rf) ** 0.5)

Best parameters:
{'n_estimators': 300, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 1.0, 'max_depth': 20}
R²: 0.9446782307717833
MAE: 24.73300175884524
RMSE: 41.854349576501804