In [116]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [117]:
data = pd.read_csv("day.csv")

In [118]:
data

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,727,2012-12-27,1,1,12,0,4,1,2,0.254167,0.226642,0.652917,0.350133,247,1867,2114
727,728,2012-12-28,1,1,12,0,5,1,2,0.253333,0.255046,0.590000,0.155471,644,2451,3095
728,729,2012-12-29,1,1,12,0,6,0,2,0.253333,0.242400,0.752917,0.124383,159,1182,1341
729,730,2012-12-30,1,1,12,0,0,0,1,0.255833,0.231700,0.483333,0.350754,364,1432,1796
730,731,2012-12-31,1,1,12,0,1,1,2,0.215833,0.223487,0.577500,0.154846,439,2290,2729

In [119]:
data.describe()

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000
mean,366.000000,2.496580,0.500684,6.519836,0.028728,2.997264,0.683995,1.395349,0.495385,0.474354,0.627894,0.190486,848.176471,3656.172367,4504.348837
std,211.165812,1.110807,0.500342,3.451913,0.167155,2.004787,0.465233,0.544894,0.183051,0.162961,0.142429,0.077498,686.622488,1560.256377,1937.211452
min,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.059130,0.079070,0.000000,0.022392,2.000000,20.000000,22.000000
25%,183.500000,2.000000,0.000000,4.000000,0.000000,1.000000,0.000000,1.000000,0.337083,0.337842,0.520000,0.134950,315.500000,2497.000000,3152.000000
50%,366.000000,3.000000,1.000000,7.000000,0.000000,3.000000,1.000000,1.000000,0.498333,0.486733,0.626667,0.180975,713.000000,3662.000000,4548.000000
75%,548.500000,3.000000,1.000000,10.000000,0.000000,5.000000,1.000000,2.000000,0.655417,0.608602,0.730209,0.233214,1096.000000,4776.500000,5956.000000
max,731.000000,4.000000,1.000000,12.000000,1.000000,6.000000,1.000000,3.000000,0.861667,0.840896,0.972500,0.507463,3410.000000,6946.000000,8714.000000

In [120]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     731 non-null    int64
 1   dteday      731 non-null    str
 2   season      731 non-null    int64
 3   yr          731 non-null    int64
 4   mnth        731 non-null    int64
 5   holiday     731 non-null    int64
 6   weekday     731 non-null    int64
 7   workingday  731 non-null    int64
 8   weathersit  731 non-null    int64
 9   temp        731 non-null    float64
 10  atemp       731 non-null    float64
 11  hum         731 non-null    float64
 12  windspeed   731 non-null    float64
 13  casual      731 non-null    int64
 14  registered  731 non-null    int64
 15  cnt         731 non-null    int64
dtypes: float64(4), int64(11), str(1)
memory usage: 91.5 KB

In [121]:
columns = ["instant", "dteday", "casual", "registered", "cnt"]

X = data.drop(columns, axis = 1)
y = data["cnt"]

In [122]:
X

,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed
0,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446
1,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539
2,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309
3,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296
4,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900
...,...,...,...,...,...,...,...,...,...,...,...
726,1,1,12,0,4,1,2,0.254167,0.226642,0.652917,0.350133
727,1,1,12,0,5,1,2,0.253333,0.255046,0.590000,0.155471
728,1,1,12,0,6,0,2,0.253333,0.242400,0.752917,0.124383
729,1,1,12,0,0,0,1,0.255833,0.231700,0.483333,0.350754
730,1,1,12,0,1,1,2,0.215833,0.223487,0.577500,0.154846

In [123]:
y

0       985
1       801
2      1349
3      1562
4      1600
       ...
726    2114
727    3095
728    1341
729    1796
730    2729
Name: cnt, Length: 731, dtype: int64

In [124]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [125]:
X_train.shape

(584, 11)

In [126]:
X_test.shape

(147, 11)

In [127]:
y_train.shape

(584,)

In [128]:
y_test.shape

(147,)

In [129]:
from sklearn.linear_model import LinearRegression

In [130]:
lr = LinearRegression()

In [131]:
lr.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'positive': False,
 'tol': 1e-06}

In [132]:
lr.fit(X_train, y_train)

LinearRegression()

In [133]:
y_pred = lr.predict(X_test)

In [134]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [135]:
print("R²:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", mean_squared_error(y_test, y_pred) ** 0.5)

R²: 0.8276670090367213
MAE: 617.3930656443378
RMSE: 831.2851545662685

In [136]:
lr.coef_

array([  524.72253637,  2023.99754659,   -38.44465798,  -391.55076626,
          72.93700256,   160.80489213,  -632.8562835 ,  2097.24783578,
        3488.04217936,  -865.43941913, -2080.54039519])

In [137]:
pd.DataFrame({
    "feature": X.columns,
    "coefficient": lr.coef_
}).sort_values("coefficient", ascending=False)

       feature  coefficient
8        atemp  3488.042179
7         temp  2097.247836
1           yr  2023.997547
0       season   524.722536
5   workingday   160.804892
4      weekday    72.937003
2         mnth   -38.444658
3      holiday  -391.550766
6   weathersit  -632.856284
9          hum  -865.439419
10   windspeed -2080.540395

In [139]:
data[["temp", "atemp"]].corr()

           temp     atemp
temp   1.000000  0.991702
atemp  0.991702  1.000000

In [140]:
from sklearn.tree import DecisionTreeRegressor

In [159]:
dtr = DecisionTreeRegressor(ccp_alpha = 0.1, max_depth=4)

In [160]:
dtr.fit(X_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.1, max_depth=4)

In [161]:
yd_pred = dtr.predict(X_test)

In [162]:
print("R²:", r2_score(y_test, yd_pred))
print("MAE:", mean_absolute_error(y_test, yd_pred))
print("RMSE:", mean_squared_error(y_test, yd_pred) ** 0.5)

R²: 0.7730224388482447
MAE: 652.9417061678444
RMSE: 954.0195503071687

In [163]:
print("Train R²:", dtr.score(X_train, y_train))
print("Test R²:", dtr.score(X_test, y_test))

Train R²: 0.8338219149017873
Test R²: 0.7730224388482447

In [164]:
dtr.feature_importances_

array([0.03692523, 0.33038141, 0.00514671, 0.        , 0.        ,
       0.        , 0.01503225, 0.47500093, 0.10105793, 0.02089432,
       0.01556124])

In [171]:
for depth in [2, 3, 4, 5, 6, 8, 10, 15, None]:

    tree = DecisionTreeRegressor(
        max_depth=depth,
        random_state=42
    )

    tree.fit(X_train, y_train)

    train_r2 = tree.score(X_train, y_train)
    test_r2 = tree.score(X_test, y_test)

    print(f"depth={str(depth):>4}, train={train_r2:.3f}, test={test_r2:.3f}")

depth=   2, train=0.691, test=0.518
depth=   3, train=0.774, test=0.693
depth=   4, train=0.834, test=0.773
depth=   5, train=0.880, test=0.801
depth=   6, train=0.919, test=0.780
depth=   8, train=0.968, test=0.802
depth=  10, train=0.987, test=0.806
depth=  15, train=0.999, test=0.811
depth=None, train=1.000, test=0.759